### ISSUE TITLE
I can't post in the help chat

### ISSUE THREAD

**Issue by grandballoon** [learn-co-curriculum/procedural-vs-oo-ruby#12]
For some reason my entries into my ask-for-help chat are just disappearing when I hit enter. Nothing gets posted to the chat.

**Comment by grandballoon** [comment]
Now I can't even open a new inquiry

**Comment by drakeltheryuujin** [comment]
Hi @grandballoon,

Are you still experiencing this issue? 
[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum itself (doesn't work,
throws a Ruby error, etc.), so I have a logged a bug report for this issue to be reviewed.

Thanks! 💙

**Comment by grandballoon** [comment]
No, all good, thanks!

**Comment by drakeltheryuujin** [comment]
@grandballoon Good to hear! Our chat system went down a couple weeks ago and was quickly resolved. Many users may have had the same issue.
